from __future__ import annotations
import re


DEFAULT_LANGUAGE = "en"
SUPPORTED_LANGUAGES = ("en", "zh")

LANGUAGE_LABELS = {
    "en": "English",
    "zh": "\u4e2d\u6587",
}


_TEXTS = {
    "en": {
        "app.title": "Cost Basis Engine",
        "app.subtitle": "Regime -> Deviation -> Inventory -> TradeIntent",
        "page_title": "Cost Basis Engine",
        "sidebar.language": "Language",
        "sidebar.inputs": "Inputs",
        "sidebar.persist_state": "Persist position state",
        "sidebar.persist_state_help": "Opt in to load/save sidebar inventory context. Leave off to keep this module idle during reruns.",
        "sidebar.state_idle": "Position persistence is off: no state file is loaded or saved during reruns.",
        "sidebar.market_source": "Market / data source",
        "sidebar.symbol": "Symbol",
        "sidebar.symbol_help_cn": "Examples: 603236, 000001",
        "sidebar.symbol_help_kr": "Examples: 005930.KS, 005935.KS",
        "sidebar.symbol_help_us": "Examples: AAPL, MSFT, NVDA",
        "sidebar.held_qty": "Target / held quantity",
        "sidebar.purchasable_qty": "Purchasable quantity",
        "sidebar.compact_mode": "Compact mode",
        "sidebar.compact_mode_help": "Show only the main decision and primary chart.",
        "sidebar.show_chart_markers": "Show chart signal markers",
        "sidebar.show_chart_markers_help": "Off by default so dense SB/BS markers do not obscure the price chart.",
        "sidebar.advanced": "Advanced",
        "sidebar.settled_sellable": "Settled sellable quantity",
        "sidebar.max_t_ratio": "Max single T ratio",
        "sidebar.max_single_trade_qty": "Max single trade quantity (0 = unlimited)",
        "sidebar.risk_preset": "Risk-limit preset",
        "sidebar.fees": "Fees and slippage",
        "fees.buy_commission_rate": "Buy commission rate",
        "fees.sell_commission_rate": "Sell commission rate",
        "fees.minimum_commission": "Minimum commission",
        "fees.stamp_tax_rate": "Stamp tax rate",
        "fees.transfer_fee_rate": "Transfer fee rate",
        "fees.other_fee_rate": "Other fee rate",
        "fees.buy_slippage_rate": "Buy slippage rate",
        "fees.sell_slippage_rate": "Sell slippage rate",
        "fees.a_share_handling_fee_bps": "A-share handling fee (bps)",
        "fees.a_share_management_fee_bps": "A-share management fee (bps)",
        "fees.a_share_transfer_fee_bps": "A-share transfer fee (bps)",
        "fees.a_share_stamp_duty_sell_bps": "A-share sell stamp duty (bps)",
        "fees.a_share_broker_commission_bps": "A-share broker commission (bps)",
        "fees.a_share_min_commission_cny": "A-share min commission (CNY)",
        "fees.us_sec_fee_per_million": "US SEC fee per million",
        "fees.us_finra_taf_per_share": "US FINRA TAF per share",
        "fees.us_finra_taf_cap_per_trade": "US FINRA TAF cap/trade",
        "fees.us_broker_commission_per_share": "US broker commission/share",
        "fees.us_broker_min_commission": "US broker min commission",
        "fees.us_platform_fee_per_order": "US platform fee/order",
        "fees.preview_price": "Fee preview price",
        "fees.preview_shares": "Fee preview shares",
        "fees.break_even_preview": "Fee preview ({market}, {shares} shares @ {price:.2f}): round-trip cost {cost:.4f}, break-even {bps:.2f} bps.",
        "sidebar.fee_profile": "Fee profile",
        "sidebar.fee_help": "Zero-fee is research-only and must be selected explicitly.",
        "sidebar.zero_fee_warning": "Zero-fee mode is for mechanics/sensitivity only; do not treat it as live guidance.",
        "sidebar.marker_cooldown": "Signal marker cooldown minutes",
        "sidebar.open_pair": "Open pair (optional)",
        "sidebar.open_pair_side": "Open pair side",
        "sidebar.open_pair_price": "Open pair first-leg price",
        "sidebar.open_pair_qty": "Open pair quantity",
        "sidebar.page": "Page",
        "sidebar.page_help": "Intraday keeps refresh lightweight; execution and research pages load slower workflows only when opened.",
        "sidebar.auto_refresh": "Auto refresh",
        "sidebar.refresh_interval": "Refresh interval seconds",
        "sidebar.enter_symbol": "Enter a symbol.",
        "state.file": "State file: {path}",
        "panel.trading_decision": "Trading decision",
        "panel.decision_summary": "Decision summary",
        "panel.intraday_market": "Intraday market",
        "panel.execution_review": "Execution / EOD review",
        "panel.execution_caption": "This page lazy-loads manual fills, broker reconciliation, execution journal, closeout review, post-trade review, live risk usage, and EOD signoff.",
        "panel.research_audit": "Research / Audit",
        "panel.threshold_experiments": "Locked-OOS threshold experiments",
        "panel.replay_mode": "Replay mode",
        "panel.source_caveats": "Data source caveats",
        "panel.data_quality": "Data quality details",
        "panel.source_grade": "Source grade",
        "panel.delay_status": "Delay status",
        "panel.trade_intent_json": "TradeIntent JSON",
        "page.intraday": "Intraday trading",
        "page.execution": "Execution / EOD review",
        "page.research": "Research / Audit",
        "status.fetch_error": "Fetch or calculation failed: {error}: {detail}",
        "status.live_mode": "Live mode: showing the latest closed minute.",
        "status.replay_mode": "Replay mode: showing model state as of selected closed minute {time}. No future bars after this time are used.",
        "status.replay_back": "Back to Live",
        "status.execution_note": "Execution panels and research/audit modules are lazy-loaded on separate pages to keep intraday refreshes light.",
        "status.execution_caption": "This page lazy-loads manual fills, broker reconciliation, execution journal, closeout review, post-trade review, live risk usage, and EOD signoff.",
        "status.strip_template": "Data: {data} | Broker confirmed: {broker_confirmed} | Latest bar: {latest_bar} | Bars: {bars} | Status: {status}",
        "status.ok": "OK",
        "status.warn": "WARN",
        "status.bad": "BAD",
        "status.broker_yes": "Yes",
        "status.broker_no": "No",
        "status.checks": "Checks",
        "status.live_note": "Live guidance remains decision support until broker-confirmed market data, holdings, and executions are checked.",
        "intent.reference_price": "Reference price",
        "intent.suggested_qty": "Suggested qty",
        "intent.net_edge": "Estimated net edge",
        "intent.cost_per_share": "Cost reduction/share",
        "intent.cost_bps": "Round-trip cost bps",
        "intent.net_edge_bps": "Net edge bps",
        "intent.inventory_ok": "Inventory OK",
        "intent.sellable_after": "Sellable after",
        "intent.inventory_delta": "Inventory delta",
        "intent.capital_required": "Capital required",
        "intent.confidence": "Confidence",
        "intent.next_action_prefix": "Next action: {value}",
        "intent.next_action": "Next action",
        "intent.primary_blocker": "Primary blocker",
        "intent.reasons": "Reasons",
        "intent.blockers": "Blockers",
        "intent.warnings": "Warnings",
        "intent.key_reasons": "Key reasons",
        "intent.broker_confirmed": "Broker confirmed",
        "decision.intent_with_conf": "{action} | confidence {confidence}",
        "summary.recommendation": "Recommendation",
        "summary.evidence": "Evidence",
        "summary.invalidation": "Invalidation",
        "summary.position_impact": "Position impact",
        "summary.caveats": "Caveats",
        "summary.no_position_impact": "Position impact: no new first-leg execution recommended.",
        "summary.action_prefix": "Action: {action}",
        "summary.confidence_prefix": "Confidence: {value}/100",
        "summary.ref_price": "Reference price: {value}",
        "summary.exec_qty": "Executable quantity: {value:,} shares",
        "summary.pair_qty": "Pair quantity to manage: {value:,} shares",
        "summary.no_exec": "Execution: wait only",
        "summary.regime": "Regime: {value}",
        "summary.vwap_dev": "VWAP deviation: {value:+.3f}%",
        "summary.turnover": "Turnover ratio: {value:.2f}x",
        "summary.recent_return": "Recent return: {value:+.3f}%",
        "summary.deviation_score": "Deviation score: {value:.2f}x",
        "summary.round_trip_cost_bps": "Round-trip cost: {value:.2f} bps",
        "summary.net_edge_bps": "Net edge after cost: {value:.2f} bps",
        "summary.edge_buffer_bps": "Required edge buffer: {value:.2f} bps",
        "summary.reason_prefix": "Reason: {value}",
        "summary.net_edge": "Estimated net edge: {value}",
        "summary.invalidation_price": "Invalidation price: {value}",
        "summary.no_invalidation": "Invalidation price: not active",
        "summary.expected_reversion": "Expected reversion zone: {value}",
        "summary.no_expected_reversion": "Expected reversion zone: not active",
        "summary.max_wait": "Max wait: {value} minutes",
        "summary.suggested_qty": "Suggested quantity: {value:,} shares",
        "summary.suggested_ratio": "Suggested ratio: {value:.2f}%",
        "summary.cost_reduction_per_share": "Estimated cost reduction/share: {value}",
        "summary.inventory_delta": "Inventory delta after first leg: {value:+,} shares",
        "summary.sellable_after": "Sellable after first leg: {value:,} shares",
        "summary.capital_required": "Capital required: {value}",
        "summary.caveat_blocker": "Blocker: {value}",
        "summary.caveat_warning": "Warning: {value}",
        "summary.cost_basis_footer": "Cost-basis reduction is not realized until both legs close, target inventory is restored, and fees/slippage are deducted.",
        "summary.performance_footer": "This is decision support, not out-of-sample profitability evidence.",
        "reason.trade_wait": "No first-leg execution until all gates pass.",
        "market.data_caption": "{market}: {symbol}; latest minute {latest}; price {price:.2f}.",
        "market.close_vs_open": "Close vs open",
        "market.vwap_deviation": "VWAP deviation",
        "market.amplitude": "Intraday amplitude",
        "market.suggested_ratio": "Suggested ratio",
        "intent.suggested_ratio_help": "Suggested qty / target qty",
        "market.bars": "Bars",
        "market.latest_bar": "Latest bar",
        "market.metrics_prefix": "Session {date}; bars {count}; latest {latest:.2f}; open {open:.2f}; VWAP {vwap:.2f}.",
        "market.no_opportunities": "No SB/BS lifecycle opportunities in the scanned minutes.",
        "market.signal_counts": "Opportunity lifecycle scan: watch {watch_sb}, probe {watch_bs}, add {add}, confirm {confirm}, close-ready {close_ready}, forced {forced}, expired {expired}, blocked {blocked}. Signal-only; no fills or realized PnL are inferred.",
        "market.signal_counts_main": "Opportunity lifecycle scan: watch {watch}, enter {enter}, exit {exit}, abort {abort}. Signal-only; no fills or realized PnL are inferred; debug table keeps the detailed states.",
        "market.signal_counts_simple": "Signal scan: SB {sb}, BS {bs}, Watch S->B {watch_sb}, Watch B->S {watch_bs}.",
        "market.marker_caption": "Chart shows full session context ({total} bars); model metrics and yellow marker use bars through {time} only.",
        "market.no_lifecycle_detail": "No signal-lifecycle rows available in the scanned interval.",
        "market.source_hint": "Yahoo minute turnover is approximated from close * volume; use it as a prototype signal only.",
        "chart.current_label": "Current: {action}",
        "chart.current_note": "Yellow marker uses the latest closed minute.",
        "chart.debug_state": "Debug state",
        "chart.regime_simple": "Regime",
        "chart.cost_bps": "Cost bps",
        "chart.net_edge_bps": "Net edge bps",
        "layer.header": "Decision layers",
        "layer.subtitle": "Read order: regime, price deviation, then inventory and capital constraints.",
        "panel.raw_json": "Raw layer JSON",
        "panel.regime": "Regime",
        "panel.deviation": "Deviation",
        "panel.inventory": "Inventory",
        "yes": "Yes",
        "no": "No",
        "na": "N/A",
        "action.no_trade": "No Trade",
        "action.watch_sb": "Watch S->B",
        "action.trigger_sb": "Trigger S->B",
        "action.watch_bs": "Watch B->S",
        "action.trigger_bs": "Trigger B->S",
        "action.manage_pair": "Manage Open Pair",
        "action.force_close": "Force Close/Restore",
        "regime.mean_reverting": "Mean Reversion",
        "regime.trend_up": "Trend Up",
        "regime.trend_down": "Trend Down",
        "regime.event_driven": "Event Driven",
        "regime.illiquid": "Illiquid",
        "regime.limit_risk": "Limit Risk",
        "regime.late_session": "Late Session",
        "regime.no_trade": "No Trade",
        "side.sb": "S->B",
        "side.bs": "B->S",
        "side.none": "None",
        "research.page_intro": "Research modules are idle by default. Run them only when you want locked-OOS validation, threshold what-if review, model-change audit, or baseline governance.",
        "research.run_scenario": "Run scenario evaluation / locked-OOS",
        "research.scenario_idle": "Scenario evaluation is idle.",
        "research.run_threshold": "Run locked-OOS threshold experiments",
        "research.threshold_idle": "Threshold experiments are idle.",
        "research.run_model_audit": "Run model-change audit",
        "research.model_audit_idle": "Model-change audit is idle.",
        "research.run_baseline_review": "Load audit baseline update review",
        "research.baseline_review_idle": "Audit baseline update review is idle.",
        "research.scenario_title": "Scenario evaluation",
        "research.scenario_caption": "Registered research comparison: no-trade baseline, simple S->B replay baseline, trigger-engine signal diagnostics, and locked OOS rows when available. This is not live-symbol performance evidence.",
        "research.assumptions": "Evaluation assumptions",
        "research.synthetic_qty": "Synthetic trade quantity: {qty:,}",
        "research.assumption_no_trade": "No-trade baseline is always shown as zero incremental trading PnL.",
        "research.assumption_simple_baseline": "Simple S->B replay is an interpretable baseline, not a production strategy claim.",
        "research.assumption_signal_only": "Trigger-engine rows are signal diagnostics only; fills and realized PnL are not inferred.",
        "research.threshold_caption": "What-if comparison against the locked-OOS audit baseline. Deltas are signal counts only and do not imply better execution or profitability.",
        "research.threshold_no_delta": "No locked-OOS metric deltas for the selected experiments.",
        "research.need_qty": "Enter a positive target / held quantity before running evaluation or threshold experiments.",
        "research.threshold_expander": "Per-scenario experiment deltas",
        "error.scenario_unavailable": "Scenario evaluation unavailable: {error}",
        "error.threshold_unavailable": "Locked-OOS threshold experiments unavailable: {error}",
        "error.model_audit_unavailable": "Model-change audit unavailable: {error}",
        "error.baseline_review_unavailable": "Audit baseline update review unavailable: {error}",
    },
}

_TEXTS["zh"] = dict(_TEXTS["en"])
_TEXTS["zh"].update({
    "app.title": "成本基准引擎",
    "app.subtitle": "市场状态 -> 偏离 -> 库存 -> 交易意图",
    "page_title": "成本基准引擎",
    "sidebar.language": "语言",
    "sidebar.inputs": "输入",
    "sidebar.persist_state": "持仓状态持久化",
    "sidebar.persist_state_help": "开启后可加载/保存左侧持仓上下文。关闭时，模块在每次刷新中保持空闲。",
    "sidebar.state_idle": "持仓持久化已关闭：本次刷新不加载也不保存持仓状态文件。",
    "sidebar.market_source": "市场/数据源",
    "sidebar.symbol": "标的",
    "sidebar.symbol_help_cn": "示例：603236、000001",
    "sidebar.symbol_help_kr": "示例：005930.KS、005935.KS",
    "sidebar.symbol_help_us": "示例：AAPL、MSFT、NVDA",
    "sidebar.held_qty": "目标/持仓数量",
    "sidebar.purchasable_qty": "可买数量",
    "sidebar.compact_mode": "精简模式",
    "sidebar.compact_mode_help": "仅显示当前核心决策与主图。",
    "sidebar.show_chart_markers": "显示图上信号标记",
    "sidebar.show_chart_markers_help": "默认关闭，避免密集 SB/BS 标记遮挡价格图。",
    "sidebar.advanced": "高级设置",
    "sidebar.settled_sellable": "T+1 可卖数量",
    "sidebar.max_t_ratio": "单次T比率上限",
    "sidebar.max_single_trade_qty": "单笔交易上限（0 表示不限制）",
    "sidebar.risk_preset": "风控预设",
    "sidebar.fees": "费用与滑点",
    "sidebar.fee_profile": "费用方案",
    "sidebar.fee_help": "零费用仅用于机制演示与敏感性分析，需显式选择。",
    "sidebar.zero_fee_warning": "零费用模式仅供研究演示，请勿作为实盘交易依据。",
    "sidebar.marker_cooldown": "信号标记冷却（分钟）",
    "sidebar.open_pair": "未平仓配对（可选）",
    "sidebar.open_pair_side": "未平仓方向",
    "sidebar.open_pair_price": "未平仓第一腿价格",
    "sidebar.open_pair_qty": "未平仓数量",
    "sidebar.page": "页面",
    "sidebar.page_help": "盘中页保持轻量刷新；执行与研究页面仅在打开后才加载较慢流程。",
    "sidebar.auto_refresh": "自动刷新",
    "sidebar.refresh_interval": "刷新间隔（秒）",
    "sidebar.enter_symbol": "请输入标的。",
    "state.file": "状态文件：{path}",
    "panel.trading_decision": "交易决策",
    "panel.decision_summary": "决策摘要",
    "panel.intraday_market": "盘中行情",
    "panel.execution_review": "执行 / 日内复盘",
    "panel.execution_caption": "该页懒加载手工回报、券商核对、执行账本、平仓签收、盘后复盘、风险使用率与日终复核。",
    "panel.research_audit": "研究 / 审计",
    "panel.threshold_experiments": "Locked-OOS 阈值实验",
    "panel.replay_mode": "回放模式",
    "panel.source_caveats": "数据源注意事项",
    "panel.data_quality": "数据质量细节",
    "panel.source_grade": "数据源评级",
    "panel.delay_status": "延迟状态",
    "panel.trade_intent_json": "TradeIntent JSON",
    "page.intraday": "盘中交易",
    "page.execution": "执行 / 日终复核",
    "page.research": "研究 / 审计",
    "status.fetch_error": "抓取或计算失败：{error}: {detail}",
    "status.live_mode": "实盘模式：基于最新已闭合分钟。",
    "status.replay_mode": "回放模式：基于已选闭合分钟 {time} 的模型状态，仅使用该时点及以前的历史分时。",
    "status.replay_back": "回到实盘",
    "status.execution_note": "执行和研究审计页面与主盘中页解耦，主刷新保持轻量。",
    "status.execution_caption": "该页按需加载手工回报、券商核对、执行流水、平仓复核、盘后复盘、风险使用率与日终签收。",
    "status.strip_template": "数据: {data} | 券商确认: {broker_confirmed} | 最新bar: {latest_bar} | Bar数: {bars} | 状态: {status}",
    "status.ok": "正常",
    "status.warn": "警示",
    "status.bad": "异常",
    "status.broker_yes": "是",
    "status.broker_no": "否",
    "status.checks": "校验项",
    "status.live_note": "实盘信号仅作决策参考，直到券商实时数据、持仓与执行确认完成。",
    "intent.reference_price": "参考价",
    "intent.suggested_qty": "建议数量",
    "intent.net_edge": "估算净价值",
    "intent.cost_per_share": "每股降本",
    "intent.cost_bps": "往返成本bps",
    "intent.net_edge_bps": "净edge bps",
    "intent.inventory_ok": "仓位可执行",
    "intent.sellable_after": "执行后可卖",
    "intent.inventory_delta": "库存变化",
    "intent.capital_required": "所需资金",
    "intent.confidence": "置信度",
    "intent.next_action_prefix": "下一步：{value}",
    "intent.next_action": "下一动作",
    "intent.primary_blocker": "关键阻断",
    "intent.reasons": "原因",
    "intent.blockers": "阻断项",
    "intent.warnings": "预警",
    "intent.key_reasons": "核心原因",
    "intent.broker_confirmed": "券商确认",
    "decision.intent_with_conf": "{action} | 置信度 {confidence}",
    "summary.recommendation": "建议",
    "summary.evidence": "证据",
    "summary.invalidation": "失效条件",
    "summary.position_impact": "仓位影响",
    "summary.caveats": "注意事项",
    "summary.no_position_impact": "仓位影响：建议当前不执行新增第一腿。",
    "summary.action_prefix": "动作：{action}",
    "summary.confidence_prefix": "置信度：{value}/100",
    "summary.ref_price": "参考价：{value}",
    "summary.exec_qty": "可执行数量：{value:,} 股",
    "summary.pair_qty": "待管理配对数：{value:,} 股",
    "summary.no_exec": "执行：仅等待",
    "summary.regime": "市场状态：{value}",
    "summary.vwap_dev": "VWAP偏离：{value:+.3f}%",
    "summary.turnover": "换手率：{value:.2f}x",
    "summary.recent_return": "近段收益：{value:+.3f}%",
    "summary.deviation_score": "偏离评分：{value:.2f}x",
    "summary.round_trip_cost_bps": "往返成本：{value:.2f} bps",
    "summary.net_edge_bps": "扣成本后净edge：{value:.2f} bps",
    "summary.edge_buffer_bps": "要求edge缓冲：{value:.2f} bps",
    "summary.reason_prefix": "原因：{value}",
    "summary.net_edge": "估算净收益：{value}",
    "summary.invalidation_price": "失效价：{value}",
    "summary.no_invalidation": "失效价：未触发",
    "summary.expected_reversion": "预期回归区间：{value}",
    "summary.no_expected_reversion": "预期回归区间：未激活",
    "summary.max_wait": "最长等待：{value} 分钟",
    "summary.suggested_qty": "建议数量：{value:,} 股",
    "summary.suggested_ratio": "建议比例：{value:.2f}%",
    "summary.cost_reduction_per_share": "预计每股降本：{value}",
    "summary.inventory_delta": "第一腿后库存变化：{value:+,} 股",
    "summary.sellable_after": "第一腿后可卖：{value:,} 股",
    "summary.capital_required": "所需资金：{value}",
    "summary.caveat_blocker": "阻断：{value}",
    "summary.caveat_warning": "警示：{value}",
    "summary.cost_basis_footer": "只有双腿平仓、目标仓位恢复且扣除全部费用滑点后，才算实现降本。",
    "summary.performance_footer": "此处仅为决策支持，不构成离线收益证明。",
    "reason.trade_wait": "未通过所有门槛前，暂不执行第一腿。",
    "market.data_caption": "{market}: {symbol}; 最新分钟 {latest}; 价格 {price:.2f}。",
    "market.close_vs_open": "收盘-开盘",
    "market.vwap_deviation": "VWAP 偏离",
    "market.amplitude": "盘中振幅",
    "market.suggested_ratio": "建议比例",
    "intent.suggested_ratio_help": "建议量 / 目标量",
    "market.bars": "分钟数",
    "market.latest_bar": "最新分钟",
    "market.metrics_prefix": "交易日 {date}；Bar数 {count}；最新 {latest:.2f}；开盘 {open:.2f}；VWAP {vwap:.2f}。",
    "market.no_opportunities": "扫描时段内未检测到 SB/BS 生命周期候选。",
    "market.signal_counts": "生命周期扫描：watch {watch_sb}，probe {watch_bs}，add {add}，confirm {confirm}，close-ready {close_ready}，forced {forced}，expired {expired}，blocked {blocked}。仅信号，不表示成交或已实现收益。",
    "market.signal_counts_main": "生命周期扫描：watch {watch}，enter {enter}，exit {exit}，abort {abort}。仅信号，不表示成交或已实现收益；详细状态保留在调试表。",
    "market.signal_counts_simple": "信号扫描：SB {sb}，BS {bs}，Watch S->B {watch_sb}，Watch B->S {watch_bs}。",
    "market.marker_caption": "图上显示全会话（{total}根）；当前模型指标及黄色线仅使用到 {time}。",
    "market.no_lifecycle_detail": "扫描区间无生命周期明细。",
    "market.source_hint": "Yahoo分钟成交额由 close*volume 近似，属于原型口径，不用于正式交易。",
    "chart.current_label": "当前：{action}",
    "chart.current_note": "黄色标记基于最新已闭合分钟。",
    "chart.debug_state": "调试状态",
    "chart.regime_simple": "简化状态",
    "chart.cost_bps": "成本bps",
    "chart.net_edge_bps": "净edge bps",
    "layer.header": "决策图层",
    "layer.subtitle": "按顺序读取：市场状态 -> 价格偏离 -> 库存与资金约束。",
    "panel.raw_json": "原始图层JSON",
    "panel.regime": "市场状态",
    "panel.deviation": "偏离",
    "panel.inventory": "库存",
    "yes": "是",
    "no": "否",
    "na": "N/A",
    "action.no_trade": "不交易",
    "action.watch_sb": "观察 S->B",
    "action.trigger_sb": "触发 S->B",
    "action.watch_bs": "观察 B->S",
    "action.trigger_bs": "触发 B->S",
    "action.manage_pair": "管理未平仓配对",
    "action.force_close": "强制平/回补",
    "regime.mean_reverting": "均值回归",
    "regime.trend_up": "上升趋势",
    "regime.trend_down": "下降趋势",
    "regime.event_driven": "事件驱动",
    "regime.illiquid": "流动性不足",
    "regime.limit_risk": "风险上限",
    "regime.late_session": "尾盘",
    "regime.no_trade": "不交易",
    "side.sb": "S->B",
    "side.bs": "B->S",
    "side.none": "无",
    "research.page_intro": "研究模块默认不运行。仅在你需要 Locked-OOS 校验、阈值敏感性、模型变更审计或基线治理时手动执行。",
    "research.run_scenario": "运行 scenario evaluation / locked-OOS",
    "research.scenario_idle": "场景评估未运行。",
    "research.run_threshold": "运行 locked-OOS 阈值实验",
    "research.threshold_idle": "阈值实验未运行。",
    "research.run_model_audit": "运行模型变更审计",
    "research.model_audit_idle": "模型变更审计未运行。",
    "research.run_baseline_review": "加载审计基线更新回顾",
    "research.baseline_review_idle": "基线更新审计未运行。",
    "research.scenario_title": "场景评估",
    "research.scenario_caption": "已注册研究对照：no-trade 基线、simple S->B 重放基线、trigger-engine 信号诊断、如可用的 locked OOS。该结果不构成实盘业绩证据。",
    "research.assumptions": "评估假设",
    "research.synthetic_qty": "模拟交易量：{qty:,}",
    "research.assumption_no_trade": "No-trade 基线视为零增量交易PnL。",
    "research.assumption_simple_baseline": "Simple S->B 重放是可解释基线，不代表生产策略收益。",
    "research.assumption_signal_only": "Trigger-engine 行仅是信号诊断，不推断成交和已实现PnL。",
    "research.threshold_caption": "与 locked-OOS 审计基线的 what-if 对比，指标变化为信号层面的差异，不代表执行收益改进。",
    "research.threshold_no_delta": "所选实验未产生可比较的 locked-OOS 指标变化。",
    "research.need_qty": "请先输入正数目标/持仓数量后再运行评估或阈值实验。",
    "research.threshold_expander": "逐场景实验差异",
    "error.scenario_unavailable": "场景评估不可用：{error}",
    "error.threshold_unavailable": "Locked-OOS 阈值实验不可用：{error}",
    "error.model_audit_unavailable": "模型变更审计不可用：{error}",
    "error.baseline_review_unavailable": "基线更新审计不可用：{error}",

    "chart.action": "动作",
    "chart.time": "时间",
    "chart.price": "价格",
    "chart.vwap": "VWAP",
    "chart.percent": "百分比",
    "chart.ratio": "指标",
    "chart.line": "线",
    "chart.state": "状态",
    "chart.signal": "信号",
    "chart.current_note": "当前动作",
    "chart.current_action": "当前动作",
    "chart.level_watch": "Watch",
    "chart.level_trigger": "Trigger",
    "chart.click_to_replay": "点击时间点以重放该分钟模型状态。",
    "chart.close": "收起",
    "chart.marker_level": "标记级别",
    "chart.reason_codes": "原因标签",
    "chart.exhaustion": "耗尽分",
    "chart.liquidity": "流动性分",
    "chart.why_not_earlier": "为何未更早触发",
    "chart.min": "分钟",
    "chart.latest_closed_minute": "最新已闭合分钟",
    "market.anchor": "锚定位",

    "execution.baseline_net_edge": "基线净边际",
    "execution.worst_stressed_edge": "最差压力边际",
    "execution.qty": "数量",
    "execution.no_sensitivity_data": "未提供敏感性数据。",
    "execution.sensitivity_caption": "交易规模放大/缩小时的净边际估算。",
    "execution.limit_ref_price": "参考价",
    "execution.cash_required": "所需资金",
    "execution.pre_trade_caption": "交易前检查清单，先确认数据和资金约束再下单。",
    "execution.reduction": "回报",
    "panel.pre_trade_checklist": "交易前清单",
    "panel.execution_quality": "执行质量",

    "execution.reduction": "成本改善",
    "execution.pre_trade_caption": "检查成交约束、风控与资金后，决定是否下单。",
    "execution.fill_qty": "填单数量",
    "execution.ticket_price_diff": "实际下单价差",
    "execution.no_sensitivity_data": "暂未生成敏感性数据。",

    "journal.action": "动作",
    "journal.manual_fills": "手工回报",
    "journal.broker_matches": "券商匹配",
    "journal.status": "状态",
    "journal.caption": "执行流水用于盘中盘后对账与复盘。",

    "broker_import.caption": "导入券商回报（如有）以核对手工回报。",
    "broker_import.matched": "匹配",
    "broker_import.broker_only": "仅券商数据",
    "broker_import.manual_only": "仅手工回报",
    "broker_import.ambiguous": "存在歧义",
    "broker_import.caption_evidence": "匹配证据与异常说明。",

    "panel.closeout_signoff": "平仓签收",
    "panel.closeout_status": "平仓状态",
    "panel.countable": "可计入",
    "panel.export": "导出",

    "closeout.closed_pairs": "已平仓配对",
    "closeout.open_pairs": "未平仓配对",
    "closeout.net_qty_delta": "净数量变化",
    "closeout.caption": "单次会话内平仓与敞口变化汇总。",

    "panel.session_closeout": "会话平仓",
    "panel.session_ledger": "会计账本",
    "ledger.realized_countable": "已实现（可计）",
    "ledger.blocked_pair_cash": "未解锁现金",
    "ledger.countable_pairs": "可计入配对",
    "ledger.no_action_day": "当日无动作",
    "ledger.caption": "将已关闭配对与仓位账务归档。",

    "panel.risk_usage": "风险使用率",
    "risk.gross_turnover_qty": "成交总量",
    "risk.open_exposure": "未平仓敞口",
    "risk.max_open_age": "最大未平仓时长",
    "risk.caption": "基于当前持仓约束的风控占用情况。",

    "panel.post_trade_review": "盘后复盘",
    "post_trade.avg_fill": "平均成交价",
    "post_trade.ticket_price_diff": "票面价差",

    "panel.position_reconciliation": "持仓核对",
    "position_recon.caption": "与券商持仓做快照核对。",
    "position_recon.form_title": "保存当前持仓快照",
    "position_recon.market_source": "市场源",
    "position_recon.symbol": "标的",
    "position_recon.total_qty": "总持仓",
    "position_recon.sellable_qty": "可卖数量",
    "position_recon.purchasable_qty": "可买数量",
    "position_recon.cash_available": "可用资金",
    "position_recon.as_of": "时间戳",
    "position_recon.note": "备注",
    "position_recon.default_note": "券商仓位快照",
    "position_recon.submit": "保存",
    "position_recon.saved": "快照已保存。",

    "panel.manual_execution": "手工成交录入",
    "manual.caption_intro": "录入手工成交后用于对账与风险快照。",
    "manual.both_legs_recorded": "第一腿与第二腿均已录入。",
    "manual.fill_qty": "成交数量",
    "manual.fill_price": "成交价格",
    "manual.broker_fees": "券商费用",
    "manual.slippage": "滑点成本",
    "manual.fill_note": "备注",
    "manual.fill_note_default": "手工成交说明",
    "manual.submit": "录入成交",

    "fees.buy_commission_rate": "买入佣金率",
    "fees.sell_commission_rate": "卖出佣金率",
    "fees.minimum_commission": "最低佣金",
    "fees.stamp_tax_rate": "印花税率",
    "fees.transfer_fee_rate": "过户费率",
    "fees.other_fee_rate": "其他费用率",
    "fees.buy_slippage_rate": "买入滑点率",
    "fees.sell_slippage_rate": "卖出滑点率",
    "fees.a_share_handling_fee_bps": "A股经手费 bps",
    "fees.a_share_management_fee_bps": "A股证管费 bps",
    "fees.a_share_transfer_fee_bps": "A股过户费 bps",
    "fees.a_share_stamp_duty_sell_bps": "A股卖出印花税 bps",
    "fees.a_share_broker_commission_bps": "A股券商佣金 bps",
    "fees.a_share_min_commission_cny": "A股最低佣金 CNY",
    "fees.us_sec_fee_per_million": "美股 SEC 费/百万",
    "fees.us_finra_taf_per_share": "美股 FINRA TAF/股",
    "fees.us_finra_taf_cap_per_trade": "美股 FINRA TAF 单笔上限",
    "fees.us_broker_commission_per_share": "美股券商佣金/股",
    "fees.us_broker_min_commission": "美股最低佣金",
    "fees.us_platform_fee_per_order": "美股平台费/单",
    "fees.preview_price": "费用预览价格",
    "fees.preview_shares": "费用预览股数",
    "fees.break_even_preview": "费用预览（{market}，{shares}股 @ {price:.2f}）：往返成本 {cost:.4f}，盈亏平衡 {bps:.2f} bps。",

    "panel.model_audit": "模型变更审计",
    "model_audit.status": "模型状态",
    "model_audit.locked_oos": "锁定的 OOS 指标",
    "model_audit.changes": "模型变更",
    "panel.baseline_update": "基线更新",
    "model_audit.no_update_needed": "无需更新基线。",
    "model_audit.update_gate": "基线更新门槛",
    "model_audit.update_gate_note": "仅当关键版本与分布变化显著时建议执行。",
    "model_audit.review_token": "复核口令",
    "model_audit.reviewer_note": "审核说明",
    "model_audit.apply_update": "应用更新",
    "threshold_experiment.caveat": "阈值实验用于研究验证，仅供决策输入。",

    "layer.shares": "股",
    "layer.score": "分数",
    "layer.shares": "股",
    "layer.not_calculated": "尚未计算",
    "layer.not_calculated_regime": "尚未计算市场状态",
    "layer.not_calculated_inventory": "尚未计算库存决策",
    "layer.blocked": "阻断",
    "layer.passed": "通过",
    "layer.candidate": "候选方向",
    "layer.no_reason": "暂无原因",
    "layer.raw_rows_more": "其余 {count} 条未展示。",

    "inventory.executable": "可执行",
    "inventory.not_executable": "不可执行",
    "inventory.shares": "股",
    "inventory.sellable_after": "交易后可卖",

    "eod.recent_journals": "今日复核",
    "eod.blocked_journals": "阻断账单",
    "eod.caption": "日终复核摘要。",

    "panel.signal_details": "信号明细",
    "panel.side": "方向",

    "status.execution_replay_note": "回放场景仅用于当时判断，不回推仓位与历史成交。",

    "broker_import.matched": "匹配成功",
    "broker_import.manual_only": "仅手工导入",
    "broker_import.broker_only": "仅券商导入",

    "ledger.no_action_day": "当日未交易",
    "execution.pre_trade_caption": "交易前检查清单（可执行性、风控和资金）。",
})

def normalize_lang(value: str | None) -> str:
    if value in SUPPORTED_LANGUAGES:
        return value
    return DEFAULT_LANGUAGE


def _humanize_key(key: str) -> str:
    text = key.replace(".", " ").replace("_", " ")
    words = [part for part in re.split(r"\s+", text) if part]
    if not words:
        return key
    return " ".join(part[:1].upper() + part[1:] for part in words)


def t(lang: str | None, key: str, **kwargs) -> str:
    normalized_lang = normalize_lang(lang)
    value = _TEXTS[normalized_lang].get(key)
    if value is None:
        value = _TEXTS[DEFAULT_LANGUAGE].get(key, _humanize_key(key))
    if kwargs:
        try:
            return value.format(**kwargs)
        except Exception:
            return value
    return value


